### ISSUE TITLE
no-build issues with compiling with RGFW

### ISSUE THREAD

**Issue by ColleagueRiley** [Code-Nycticebus/claymore#14]
When testing building claymore I found a few issues. 

1) `strndup` gave an implicit declaration error, this is because it's for a newer version of C. RGFW should probably support at least C99, so I'll remove the function.

2) `setenv`, implicit declaration,
3) nanosleep`, implicit declaration, 

Both of these are unix functions that seem to be excluded based on the c version. RGFW should probably include a declaration of these functions internally.

**Comment by ColleagueRiley** [comment]
These issues have been fixed by the newest version of RGFW

**Comment by Code-Nycticebus** [comment]
Thank you so much!
