### ISSUE TITLE
Add a memory tracker. i need to profile where i allocate memory.

### ISSUE THREAD

**Issue by Code-Nycticebus** [Code-Nycticebus/claymore#4]
Right now its unknown how much memory i heap allocate and how much memory i stack allocate.

i only got info on the 2d renderer

**Comment by alexlnkp** [comment]
> Right now its unknown how much memory i heap allocate and how much memory i stack allocate.
> 
> i only got info on the 2d renderer

Why not just use valgrind?

**Comment by Code-Nycticebus** [comment]
Well this is a very old issue i opened. Even before i created [cebus](https://github.com/Code-Nycticebus/cebus) and an 'arena' allocator.
The idea was that the user can also profile their own allocated memory. 

Should be pretty easy to see now since i added `arena_size()` to cebus.

Thank you for the contribution. Much appreciated.
